version: "3.9"
services:
  putichat:
    build: .
    ports:
      - "8888:8887"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: sh -c "nvidia-smi && python3 /app/text-generation-webui/server.py --share --settings /app/settings.yaml --model /app/text-generation-webui/models/Llama-2-7b-chat-hf"
